# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: I2 Intro Neuro/AI
tagline: I2's Introductory Course!
description: Welcome to Interactive Intelligence's Introduction to Neuro/AI crash course!
author: Interactive Intelligence
baseurl: '/' # the subpath of your site, e.g. /blog
url: 'https://course.uw-i2.org' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

# LaTeX rendering via "katex" (KaTeX, default) or "mathjax" (MathJax) or "none" / "off" (NO rendering)
latex: katex

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.4.2
color_scheme: dark
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  UW Interactive Intelligence Website:
    - 'https://interactive-intelligence.github.io'
footer_content:

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
  wiki:
  graduates:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement
  - scope:
      path: ''
      type: graduates
    values:
      layout: staffer
      subpath: '/assets/images/'

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: true
  blanklines: true
  profile: false
